### PR TITLE
correct ANN and SVANN header line `Number` entry to `UNBOUND`

### PR DESCRIPTION
**Pull request by dlaehnemann**
Set Number in ANN VCF header lines to '.', i.e. to `UNBOUND`, as multiple annotations may occur comma-separated per VCF entry. I ran into this in downstream parsing that got confused by the current `Number=1` in the header, which expects exactly one entry in the `ANN` field, but often finds more.

These are the only places I found, where header lines for the `ANN` field are defined -- but please double-check if I have missed anything. Also, I think I am loading the correct `htsjdk` classes, but I have not tested these changes. And I am assuming, that the `SVANN` `INFO` field can also possibly have multiple entries per `VCF` entry and thus requires the same change.

### CODE REVIEW

**Comment by dlaehnemann** [comment]
In case it's needed for reference, here's the respective part in the VCF 4.3 spec:

https://github.com/samtools/hts-specs/blob/103fd9988b3ce91f17f8d5bb52671291f408d007/VCFv4.3.tex#L137-L150

Also, another option to implement this, is to switch behaviour depending on the command-line option `--show-all`. I.e., I noticed the problem with the header line in a case where I was using `--show-all`, so that multiple `ANN` entries were created. In case this is not used, the `jannovar` default is to only output one most pathogenic `ANN` entry. So in this case, `Number=1` would be a valid specification. But just switching to `Number=.` in general seems the easiest way to go...

**Comment by dlaehnemann** [comment]
@holtgrewe, @visze Just a quick bump-up, in case this was overlooked.

**Comment by dlaehnemann** [comment]
@holtgrewe Sorry for the nagging, just don't want this PR to be overlooked...

**Comment by holtgrewe** [comment]
@dlaehnemann sorry for not following up on this, will do so next week

**Comment by holtgrewe** [comment]
closing in favour of #462

**Pull request closed without merging**
