### PR TITLE
Preparing annotation of SVs with Jannovar

### PR DESCRIPTION
**Pull request by holtgrewe**
This branch/PR attempts implement SV annotation for Jannovar for Jannovar.
As it's touching `VariantEffect`, it pulls over some (yet unused) variant effects from the [consequence predictions from VEP](https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html).

It is not within scope to parse out functional non-coding elements/regulatory regions etc. from RefSeq or ENSEMBL.

- [ ] extend `VariantEffect` with appropriate types for commonly detectable SVs.
    - missing: `tandem_duplication`
    - missing: `mobile_element_deletion`
    - missing: `mobile_element_insertion`
    - missing: `junction` (for breakpoint)
- [ ] prepare effects for non-coding variants (ENSEMBL regulatory regions are currently not properly represented, the RefSeq Functional Elements are also ignored)
- [ ] implement annotation of SVs from VCF v4.3 insofar they affect transcripts
    - [ ] `DEL`
    - [ ] `INS`
    - [ ] `DUP`
    - [ ] `INV`
    - [ ] `CNV`
    - [ ] `BND` -- as `junction`/`
    - [ ] `DUP:TANDEM`
    - [ ] `DEL:ME`
    - [ ] `INS:ME`

### CODE REVIEW

**Comment by holtgrewe** [comment]
@pnrobinson @julesjacobsen what do you think?

**Comment by holtgrewe** [comment]
OK, merging this although the SV annotation is incomplete.

@visze @pnrobinson Truth be told, I'd be happier with IntelliJ after using PyCharm for quite some time now and conversion to Google Java style will be easier now before making that switch (we never got the "Jannovar Style" to work properly with IntelliJ.

**Comment by julesjacobsen** [comment]
@holtgrewe regarding IntelliJ - I've been using it for about five or so years now and it's excellent. I even managed to convert @pnrobinson to using it from Emacs! It has very readable default formatting, which follows the official java style-guide (the Google one is different) and I can't see a decent reason to not follow the official/default IntelliJ version.

**Comment by holtgrewe** [comment]
I prefer using Google style as it uses spaces and not tabs.

**Comment by holtgrewe** [comment]
Also, finding a CLI autoformatter for Google style is easy.

**Comment by julesjacobsen** [comment]
But they are spaces - 4 of them which just look like a tab. Still, it's your project, so I'm not going to complain any more - I prefer the change to the old style.

**Comment by holtgrewe** [comment]
Jules, actually it's 2.

**Comment by julesjacobsen** [comment]
2? Spaces? I meant IntelliJ default = 4 spaces. But that's cool Google formatting is fine.

**Pull request merged**
