### PR TITLE
Google style

### PR DESCRIPTION
**Pull request by holtgrewe**
This

- applies Google Java Style
- enables building on Travis CI using JDK 8 to 11, including OpenJDK early-access
- ~~enforces style in CI using checkstyle~~
- runs checkstyle in CI without enforcing it

### CODE REVIEW

**Comment by holtgrewe** [comment]
@pnrobinson So we're testing build compatibility now. I think we still would have to build the JARs on Maven central with Java 8 as long as we support it (I would expect JAR backward compatibility but no forward compatibility).

**Comment by visze** [comment]
@holtgrewe be aware of  #420 before merging

**Comment by holtgrewe** [comment]
It's too painful to retrofit Jannovar. Giving up. Will cherry pick the good stuff from the Travis CI changes, though.

**Comment by holtgrewe** [comment]
Giving up in favour of #427

**Pull request closed without merging**
