### PR TITLE
Fix for #285 and a few TODOs to consider.

### PR DESCRIPTION
**Pull request by julesjacobsen**
Fix for #285

### CODE REVIEW

**Comment by julesjacobsen** [comment]
This would be really good as a 0.18.1 hotfix as I think the multi-sample inheritance mode checking is broken.

**Comment by visze** [comment]
I do not agree with the changes. This does not consider the following: `./.`

This can be het, homref and altref

**Comment by julesjacobsen** [comment]
So do you mean you think that ``./.`` should return true instead of false in this test?

```java
    @Test
    public void testDiploidNoCallHom() {
	Genotype genotype = new Genotype(Arrays.asList(-1, -1));
	assertEquals(2, genotype.getPloidy());
	//TODO: Should a diploid with an unobserved allele really be classed as a diploid?
	assertFalse(genotype.isMonoploid());
	assertTrue(genotype.isDiploid());

	assertFalse(genotype.isHet());
	assertFalse(genotype.isHomRef());
	assertFalse(genotype.isHomAlt());
    }
```

In the ``0/.`` case, the implementation also returns false in all cases:

```java
    @Test
    public void testDiploidNoCallHetAlt() {
	Genotype genotype = new Genotype(Arrays.asList(0, -1));
	assertEquals(2, genotype.getPloidy());
	//TODO: Should a diploid with an unobserved allele really be classed as a diploid?
	assertFalse(genotype.isMonoploid());
	assertTrue(genotype.isDiploid());

	assertFalse(genotype.isHet());
	assertFalse(genotype.isHomRef());
	assertFalse(genotype.isHomAlt());
    }
```
Both these are consistent with the behaviour of the HTSJKD Genotype implementation.

**Comment by visze** [comment]
Wait. hold on. Ok I think at some point we decided not to use ./. and any het/hom etc (did we decide that? I am not quite sure). So your first test might be correct.

The second one not! it should be:

```java
    @Test
    public void testDiploidNoCallHetAlt() {
	Genotype genotype = new Genotype(Arrays.asList(0, -1));
	assertEquals(2, genotype.getPloidy());
	//TODO: Should a diploid with an unobserved allele really be classed as a diploid?
	assertFalse(genotype.isMonoploid());
	assertTrue(genotype.isDiploid());

	assertTrue(genotype.isHet());
	assertTrue(genotype.isHomRef());
	assertFalse(genotype.isHomAlt());
    }
```

This is the only way it makes sense to interpret the value '0/.' It is definitly not a `no call` It can be `het` or `hom ref`

**Comment by visze** [comment]
I will change it that it works an show you the differences via a pull request. But thanks for spotting this!

**Comment by julesjacobsen** [comment]
Can we settle on ``mixed``? I agree its not a ``no call``, but at the same time, it's neither really a ``het`` or ``hom ref`` as one allele wasn't called so you don't know.

Again I'll point you to the previous definition you were using:

```java
protected GenotypeType determineType() {
        // TODO -- this code is slow and could be optimized for the diploid case
        final List<Allele> alleles = getAlleles();
        if ( alleles.isEmpty() )
            return GenotypeType.UNAVAILABLE;

        boolean sawNoCall = false, sawMultipleAlleles = false;
        Allele observedAllele = null;

        for ( final Allele allele : alleles ) {
            if ( allele.isNoCall() )
                sawNoCall = true;
            else if ( observedAllele == null )
                observedAllele = allele;
            else if ( !allele.equals(observedAllele) )
                sawMultipleAlleles = true;
        }

        if ( sawNoCall ) {
            if ( observedAllele == null )
                return GenotypeType.NO_CALL;
            return GenotypeType.MIXED;
        }

        if ( observedAllele == null )
            throw new IllegalStateException("BUG: there are no alleles present in this genotype but the alleles list is not null");

        return sawMultipleAlleles ? GenotypeType.HET : observedAllele.isReference() ? GenotypeType.HOM_REF : GenotypeType.HOM_VAR;
    }
```

the key part here is: 

```java
    if ( sawNoCall ) {
        if ( observedAllele == null )
            return GenotypeType.NO_CALL;
        return GenotypeType.MIXED;
    }
```

**Comment by julesjacobsen** [comment]
I forgot to add this case:

```java
    @Test
    public void testDiploidMultiSampleMixed() {
	Genotype genotype = new Genotype(Arrays.asList(2, -1));
	assertEquals(2, genotype.getPloidy());
	assertFalse(genotype.isHet());
	assertFalse(genotype.isHomRef());
	assertFalse(genotype.isHomAlt());
    }
```

Should there be a ``isMixed()`` and ``isNoCall()`` methods too perhaps?

**Comment by visze** [comment]
yep. i saw it and added it. 3 minutes and you see a new pull request. now I guess it is really fine!

**Comment by visze** [comment]
P.S.: you test class helped a lot!

**Comment by visze** [comment]
see pull request #288

**Comment by pnrobinson** [comment]
One comment -- is MIXED a good terminology? I would think that INDETERMINATE is better, because we simply do not know what the genotype is; it is not the case that 1/. is both het and hom, for instance.

**Comment by holtgrewe** [comment]
Hm, I think this is really an issue of the VCF standard coding for different things.

For example, I think some people encode "ALT" on chrX for males as "./1" (as you might have both males and females in the same multi-VCF file) instead of "1/1".

Also, "1/2" might be split into "1/." and "2/." for certain VCF normalization programs/steps.

One common way of interpreting things is that "./." is no-call and "1/." is the same as "1/0".

Anyway, just my two cents. I have no strong opinion here (as I think that "1/2" are very rare and I guess almost always caused by segmental duplication/paralogues). I only think that these things have to be properly documented and be overall consistent and reasonable.

**Comment by visze** [comment]
As described in the documentation we want to retain sensitivity maybe on the loose of specificity. So that's why we interpret ./1 in het or in homAlt (only for the inheritance filtering) If the user wants to have ./1 as only as 0/1 he has to change it before running jannovar

**Pull request closed without merging**
