### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by visze**
problems using different java versions

### CODE REVIEW

**Comment by visze** [comment]
it seem to work only on java 8 right now...

**Comment by holtgrewe** [comment]
We should probably bump projectlombok dependency here.

**Comment by visze** [comment]
> 
> 
> We should probably bump projectlombok dependency here.

what do you mean by this?

**Comment by holtgrewe** [comment]
I think #476 is a better alternative.

**Comment by visze** [comment]
close because of #476

**Pull request closed without merging**
