### PR TITLE
Refactor of Ensembl Parser

### PR DESCRIPTION
**Pull request by julesjacobsen**
This version requires a lot less RAM than the original implementation - will now happily run in 1GB instead of 8GB.

I loaded in all the input and output files need ed to test this too. Not sure if you want to keep them or not as a few of them are a shade over the 50MB filesize limit.

### CODE REVIEW

**Comment by holtgrewe** [comment]
Hi Jules,

thanks for the patch. I'm seeing some problems before merging it, though.

First of all, `HG19RefDictBuilder` should probably not contain the `"MT"` entry as this is is for hg38...

Second, we should not put large files into the repository, please. Please cut out some smaller data parts for testing (e.g., using the new feature for specifying gene IDs to limit download to in the download command).

Third, what is happening with the PAR transcripts? Maybe @roland-ewald could have a look.

Limiting memory requirements for building the databases is not a critical problem from my point of view, so I think we should clarify all issues before merging even if this means pushing this PR after the next release.

**Comment by julesjacobsen** [comment]
Ah I see now that the Hg19RefDictBuilder is actually a utility class for test use - shouldn't this be in ```src/test``` rather than ```src/main``` in case someone, like myself, ends up using it in production code?
I have been mistakenly using this as an easy means to map from contig name to integer.

What is hg38 specific about 'MT'? It is used as the Ensembl mitochondrial chromosome symbol in the file ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.105/Assembled_chromosomes/chr_accessions_GRCh37.p13

OK, I'll cut down the download files. I added them all in order to do a thorough comparison of the old and new code.

As for the PAR transcripts - I simply replicated what the original code was doing. I agree it does seem odd though.

**Comment by holtgrewe** [comment]
Hi Jules,

TBH, the `Hg19RefDictBuilder` was used in some code for generating `.ser` files mostly. It should go into the tests rather than main.

NVM the "MT" comment then. I'm always getting confused by the different versions that the mitochondrial chromosome is used. Good catch adding it!

Thanks for the detailed comparison of old and new files but I think with respect to repo size and CI tests, it's better to have smaller files.

Regarding PAR, let's keep it the way you did it unless @roland-ewald complains? :)

**Comment by julesjacobsen** [comment]
Yes, the ```Hg19RefDictBuilder``` is only used in tests. I'll move it into tests.

How big a file will you accept? It's going to be a bit of a pain in the arse to trim out all the required pieces.

**Comment by holtgrewe** [comment]
@julesjacobsen it's always a tradeoff. What parts do you need?

**Comment by julesjacobsen** [comment]
Enough to cover all the conditions in the parsers. I've managed to trim down the refseq data to something tiny. Will do the ensembl data next.

I think these refseq transcripts cover most cases:
```
STRN NM_003162.3(2:g.37064841_37193615)
STRN XM_005264519.1(2:g.37070934_37193673)
SLC25A6 NM_001636.3(Y:g.1455045_1461039)
SH3RF3 NM_001099289.1(2:g.109745997_110107395) 
```

**Comment by holtgrewe** [comment]
Excellent, I'd say enough data to show a few dozen genes would be OK to have and you appear to be very much below that.

**Comment by julesjacobsen** [comment]
@holtgrewe there you go, no large files.

**Comment by holtgrewe** [comment]
Excellent, thanks a lot. Do you mind if I take it from here and rebase and squash things before merging?

Does my patch for the ENSG-Entrez mapping work for you? #434

**Comment by julesjacobsen** [comment]
@holtgrewe nope - squash away. Will need to check with Damian about the #434 change. He should be about tomorrow.

**Comment by holtgrewe** [comment]
Closing in favour of #434

**Pull request closed without merging**
