### PR TITLE
AnnotationList updates

### LINKED ISSUE #143: Updates to AnnotationList
* rename to VariantAnnotations
* add GenomeChange
* remove List interface

### PR DESCRIPTION
**Pull request by holtgrewe**
Should fix #143

### CODE REVIEW

**Comment by julesjacobsen** [comment]
In class ```VariantAnnotations```

```java
public VariantEffect getHighestImpactEffect() {
	final Annotation anno = getHighestImpactAnnotation();
	if (anno.getEffects().isEmpty())
		return VariantEffect.SEQUENCE_VARIANT;
	else
		return anno.getEffects().first();
}
```
```anno.getEffects().isEmpty()``` can throw a NullPointer due to
```java
public Annotation getHighestImpactAnnotation() {
	if (entries.isEmpty())
		return null;
	else
		return entries.get(0);
}
```

**Comment by julesjacobsen** [comment]
Less important, but I think this matters from a readability viewpoint and self-describability of the API:

In class ```VariantAnnotator```
```java
public VariantAnnotations buildAnnotationList(GenomeVariant change) throws AnnotationException 
```
would read better as 
```java
public VariantAnnotations buildAnnotations(GenomeVariant change) throws AnnotationException 
```
Similarly for ```VariantContextAnnotator```
```java
public ImmutableList<VariantAnnotations> buildAnnotationList(VariantContext vc) throws InvalidCoordinatesException {
```
as
```java
public ImmutableList<VariantAnnotations> buildAnnotations(VariantContext vc) throws InvalidCoordinatesException {
```
and
```java
public VariantAnnotations buildErrorAnnotationList(GenomeVariant change) {
```
as
```java
public VariantAnnotations buildErrorAnnotations(GenomeVariant change) {
```

**Comment by holtgrewe** [comment]
:+1: @julesjacobsen I warmly welcome more readability and usability suggestions

**Comment by julesjacobsen** [comment]
Another one in ``` VariantAnnotations ```
```
public GenomeVariant getChange() { 
	return change; 
} 
```
would be better named ```getGenomeVariant()``` or ```getVariant()```. I think there are several instances of this from when ```GenomeChange``` was renamed to ```GenomeVariant```

**Pull request merged**
